name: campus_food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  razorpay_flutter: ^1.3.5
  fl_chart: ^0.63.0
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_local_notifications: ^14.1.1
  firebase_core: 2.13.1
  firebase_auth: 4.6.2
  cloud_firestore: 4.8.0
  cloud_functions: 4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
