// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:web:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    authDomain: 'campus-food-app-75fc7.firebaseapp.com',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:android:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:ios:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
    iosClientId: '44180746459-kn75ukuldtgldk7lrnc99i3ais4f2u1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus_food_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:macos:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
    iosClientId: '44180746459-kn75ukuldtgldk7lrnc99i3ais4f2u1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus_food_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:windows:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAqUYAWsKCLqySJidUzTUKViPdVwLtXWkc',
    appId: '1:44180746459:linux:2f31d5dc18924d26e8dcfe',
    messagingSenderId: '44180746459',
    projectId: 'campus-food-app-75fc7',
    storageBucket: 'campus-food-app-75fc7.firebasestorage.app',
  );
}